### PR TITLE
ReduxDevTools - Updated to support any browsers

### PR DESCRIPTION
**Pull request by y1bs**
Updated ReduxDevTools to support any browsers with or without the extension

# Feature

Use Case: -
Feature ID : -
Feature: Redux Dev tools extension
Figma link for wireframe: -

# Changelog:
- added redux devtools extension to yarn. Link: https://yarnpkg.com/package/redux-devtools-extension
- Edited src/index.js with compose

# Merge/Review Order
-

These other PRs should be merged or reviewed first
-

This PR blocks these other PRs
-

## Checklist:

- [ ] Merged latest develop
- [ ] PR title makes sense

### CODE REVIEW

**Review by natalieloke — COMMENTED** [review]
what would happen if one alr has the extension installed in the browser? 

currently the one in my browser is a diff version
Screenshot 2021-02-17 at 10 52 50 AM

**Comment by y1bs** [comment]
> what would happen if one alr has the extension installed in the browser?
> 
> currently the one in my browser is a diff version
> Screenshot 2021-02-17 at 10 52 50 AM

No issues, the installation of the extension support on the source codes is to support the usage of the browser redux tool. It also helps prevent any error if the extension was not downloaded on browser. If i'm not wrong they're separate things, so it does not matter if your browser extension are of a different version.

**Review by natalieloke — APPROVED** [review]

**Comment by y1bs** [comment]
Thanksie!

**Comment by y1bs** [comment]
I can share more about it later during the meeting!

**Pull request merged**
