### PR TITLE
H.3.1 view transaction history (sensei and student) functionality

### PR DESCRIPTION
**Pull request by natalieloke**
# Feature

Use Case: H.3.1 view transaction history 
Feature ID : 9
Feature: Purchasing
Figma link for wireframe:

# Changelog:
- see commit log
generally some refactoring to let sensei and student have the same transactions page (sensei will show wallet component conditionally) + refactoring to constants for filters

## Checklist:

- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):
**Student**
Screenshot 2021-03-20 at 12 38 09 AM

**Sensei**
top half of page
Screenshot 2021-03-20 at 12 42 56 AM
bottom half of page
Screenshot 2021-03-20 at 12 43 01 AM

_to see how the page changes when sensei makes a withdraw request_
<a href="https://www.loom.com/share/92a412c32cf642b99d93a8dc581e24a0"> <p>Digi Dojo | View Wallet | Withdraw | View Transactions (Sensei) - Watch Video</p>  </a>

### CODE REVIEW

**Review by rawrrencee — APPROVED** [review]
nice!! thanks for the video, helps make review fast n ez

**Comment by rawrrencee** [comment]
Hi @natalieloke, for the lines referenced here, in the Wallet, I was wondering if its possible to do a dynamic width for the withdraw button? As I feel it might be too long on desktop but its a good width on mobile.

https://github.com/rawrrencee/is4103-frontend/blob/55fdd211fa849195e065956d8f8d61db08fe0913/src/components/Sensei/Wallet/index.js#L114-L117

```
        <div className="row d-flex">
          <div className="col-12">
            <WithdrawButton />
          </div>
```
Suggestion for testing (not tested, feel free to modify it, I think as long as the width of the btn is reduced its ok!):


```
        <div className="row justify-content-center">
          <div className="col-12 col-md-6">
            <WithdrawButton />
          </div>
```

**Review by y1bs — APPROVED** [review]
Looks Good!

**Comment by natalieloke** [comment]
> Hi @natalieloke, for the lines referenced here, in the Wallet, I was wondering if its possible to do a dynamic width for the withdraw button? As I feel it might be too long on desktop but its a good width on mobile.
> 
> https://github.com/rawrrencee/is4103-frontend/blob/55fdd211fa849195e065956d8f8d61db08fe0913/src/components/Sensei/Wallet/index.js#L114-L117
> 
> ```
>         <div className="row d-flex">
>           <div className="col-12">
>             <WithdrawButton />
>           </div>
> ```
> 
> Suggestion for testing (not tested, feel free to modify it, I think as long as the width of the btn is reduced its ok!):
> 
> ```
>         <div className="row justify-content-center">
>           <div className="col-12 col-md-6">
>             <WithdrawButton />
>           </div>
> ```

@rawrrencee how's this? this is with col-md-6 as per your suggestion
<a href="https://www.loom.com/share/b3f52d160a0648ae88e554a44b44ae18">
    <p>Digi Dojo | Sensei Wallet Withdrawal Button - Watch Video</p>
    
  </a>
  
if this change is ok and i'll commit these changes and re-request for a review

**Comment by rawrrencee** [comment]
> > Hi @natalieloke, for the lines referenced here, in the Wallet, I was wondering if its possible to do a dynamic width for the withdraw button? As I feel it might be too long on desktop but its a good width on mobile.
> > https://github.com/rawrrencee/is4103-frontend/blob/55fdd211fa849195e065956d8f8d61db08fe0913/src/components/Sensei/Wallet/index.js#L114-L117
> > 
> > ```
> >         <div className="row d-flex">
> >           <div className="col-12">
> >             <WithdrawButton />
> >           </div>
> > ```
> > 
> > 
> > Suggestion for testing (not tested, feel free to modify it, I think as long as the width of the btn is reduced its ok!):
> > ```
> >         <div className="row justify-content-center">
> >           <div className="col-12 col-md-6">
> >             <WithdrawButton />
> >           </div>
> > ```
> 
> @rawrrencee how's this? this is with col-md-6 as per your suggestion
> [ ](https://www.loom.com/share/b3f52d160a0648ae88e554a44b44ae18)
> 
> [Digi Dojo | Sensei Wallet Withdrawal Button - Watch Video](https://www.loom.com/share/b3f52d160a0648ae88e554a44b44ae18)
> 
> [  ](https://www.loom.com/share/b3f52d160a0648ae88e554a44b44ae18)
> if this change is ok and i'll commit these changes and re-request for a review

HAHA OMG I feel it still looks weird HAHAH omg do u mind I will explore the med screen position (just gonna try 2 more positions of the btn) after u merge this branch? Im thinking either left align or right align (prolly right)  instead of center align for medium screens(keep center align for mobile)

**Comment by natalieloke** [comment]
> > > Hi @natalieloke, for the lines referenced here, in the Wallet, I was wondering if its possible to do a dynamic width for the withdraw button? As I feel it might be too long on desktop but its a good width on mobile.
> > > https://github.com/rawrrencee/is4103-frontend/blob/55fdd211fa849195e065956d8f8d61db08fe0913/src/components/Sensei/Wallet/index.js#L114-L117
> > > 
> > > ```
> > >         <div className="row d-flex">
> > >           <div className="col-12">
> > >             <WithdrawButton />
> > >           </div>
> > > ```
> > > 
> > > 
> > > Suggestion for testing (not tested, feel free to modify it, I think as long as the width of the btn is reduced its ok!):
> > > ```
> > >         <div className="row justify-content-center">
> > >           <div className="col-12 col-md-6">
> > >             <WithdrawButton />
> > >           </div>
> > > ```
> > 
> > 
> > @rawrrencee how's this? this is with col-md-6 as per your suggestion
> > [ ](https://www.loom.com/share/b3f52d160a0648ae88e554a44b44ae18)
> > [Digi Dojo | Sensei Wallet Withdrawal Button - Watch Video](https://www.loom.com/share/b3f52d160a0648ae88e554a44b44ae18)
> > [  ](https://www.loom.com/share/b3f52d160a0648ae88e554a44b44ae18)
> > if this change is ok and i'll commit these changes and re-request for a review
> 
> HAHA OMG I feel it still looks weird HAHAH omg do u mind I will explore the med screen position (just gonna try 2 more positions of the btn) after u merge this branch? Im thinking either left align or right align (prolly right) instead of center align for medium screens(keep center align for mobile)

LOL ok suree - merged alr! @rawrrencee

**Pull request merged**
